/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProcesarRouteImport } from './routes/procesar'
import { Route as PruebaRouteImport } from './routes/prueba'
import { Route as ProyectosIdRouteImport } from './routes/proyectos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcesarRoute = ProcesarRouteImport.update({
  id: '/procesar',
  path: '/procesar',
  getParentRoute: () => rootRouteImport,
} as any)
const PruebaRoute = PruebaRouteImport.update({
  id: '/prueba',
  path: '/prueba',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosIdRoute = ProyectosIdRouteImport.update({
  id: '/proyectos/$id',
  path: '/proyectos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/procesar': typeof ProcesarRoute
  '/prueba': typeof PruebaRoute
  '/proyectos/$id': typeof ProyectosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/procesar': typeof ProcesarRoute
  '/prueba': typeof PruebaRoute
  '/proyectos/$id': typeof ProyectosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/procesar': typeof ProcesarRoute
  '/prueba': typeof PruebaRoute
  '/proyectos/$id': typeof ProyectosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/procesar' | '/prueba' | '/proyectos/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/procesar' | '/prueba' | '/proyectos/$id'
  id: '__root__' | '/' | '/procesar' | '/prueba' | '/proyectos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProcesarRoute: typeof ProcesarRoute
  PruebaRoute: typeof PruebaRoute
  ProyectosIdRoute: typeof ProyectosIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procesar': {
      id: '/procesar'
      path: '/procesar'
      fullPath: '/procesar'
      preLoaderRoute: typeof ProcesarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prueba': {
      id: '/prueba'
      path: '/prueba'
      fullPath: '/prueba'
      preLoaderRoute: typeof PruebaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/$id': {
      id: '/proyectos/$id'
      path: '/proyectos/$id'
      fullPath: '/proyectos/$id'
      preLoaderRoute: typeof ProyectosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProcesarRoute: ProcesarRoute,
  PruebaRoute: PruebaRoute,
  ProyectosIdRoute: ProyectosIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
